name: Reportar un error
description: ¿Has encontrado un error? Repórtalo aquí
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
     value: |
Muchas gracias por tu ayuda. Sin embargo, necesitamos una cierta cantidad de información para ayudarnos.
  - type: checkboxes
    attributes:
      label: "Lista de comprobaciones a realizar antes de validar la apertura del informe de error"
      description:Asegúrese de haber completado lo siguiente, de lo contrario su informe puede ser rechazado
      options:
        - label: Logré reproducir el error en Oni Studio Launcher Beta Test (sin mis modificaciones)
          required: true
        - label: Mi código respeta la Licencia Universal Creative Commons Zero v1.0
          required: true
        - label: Mi código cumple con los términos de uso de Oni Studio Beta Test
          required: true
        - label: Logré reproducir el error en la última versión de Oni Studio Launcher Beta Test
          required: true
  - type: dropdown
    attributes:
      label: Sistema operativo
      options:
        - Windows
        - macOS
        - Linux (Basado en Debian/Ubuntu)
        - Linux (Otros)
    validations:
      required: true
  - type: input
    attributes:
      label: Versión del sistema operativo
      placeholder: "Ejemplo: Windows 11 Professional 21H2 compilación 22000.739"
    validations:
        required: true
  - type: input
    attributes:
      label: Hash de la confirmación en la que se encuentra el error
      placeholder: 84d7881b67ecf6088205eca6723bfb19bf2a5f0d
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Una descripción de lo que debería suceder.
      placeholder: El launcher debe...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento actual
      description: Una descripción de lo que está sucediendo con el error.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instrucciones para replicar el objetivo.
      placeholder: |

        1. Abre el lanzador
        2. Vaya al menú xyz
        3. Haga clic en abc
        4. Observa
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notas adicionales
      placeholder: Detalles adicionales de errores, cualquier cosa que pueda ser útil
    validations:
      required: false
